#
# Module Manifest for Modules.Download.Files
#
# Generated by V1ola1ne
#
# Generated on 20.06.2024


@{

    # Script module or binary module file associated with this manifest.
    RootModule = "Modules.Download.Files.psm1"

    # Author of this module
    Author = 'V1ola1ne'

    # Version number of this module.
    ModuleVersion = '1.0.0'

    # Description of the functionality provided by this module
    Description = 'This provides the (almost) fastest Way to Download Files trough Powershell'

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = 'Invoke-FileDownload'

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()

    # Variables to export from this module
    AliasesToExport = @()

    # Modules Required to Wokr
    RequiredModules = @('Microsoft.PowerShell.ThreadJob')

    ProjectUri = "https://github.com/V1ola1ne/Download-Files-PS-Module"
}